### ISSUE TITLE
Script.js loading issue

### ISSUE THREAD

**Issue by oyejateen** [TheNewC0der-24/Music-Website#1]
Hey!! I was trying to edit, refine and redesign this wonderful project but while i try to add some js script and re-run the project, the website stuck at pre-loader page and i could not be able make changes. Can you please help me out in it.

> In web~ it just showing pre-loder page

![Screenshot_2022-10-01-09-56-58-71](https://user-images.githubusercontent.com/75193966/193392498-932d636e-e21b-4830-944c-f6ac7719944b.png)

> I have tried to make the following changes 

![Screenshot_2022-10-01-09-57-34-12](https://user-images.githubusercontent.com/75193966/193392501-68fcc3ac-8cf7-4e46-a710-d2d511b0e5f8.png)

**Comment by TheNewC0der-24** [comment]
Thanks, [TEDDY6969](https://github.com/TEDDY6969)
For trying to edit, refine and redesign this project. Can you please let me know that what use case you are thinking, or we can say that can you please explain to me what changes you want to try?

**Comment by oyejateen** [comment]
Thanks @TheNewC0der-24 for getting back to me. İ really loved this project but as it plays only one song ~ i like me better(it's one of ma fav songs). İ was just trying to do something with which it can play multiple songs right.

İ was using window onload function so that when a user open the website our program will do maths random from 3-4 songs it will load one. Each time when user will reload same thing will happen again and again Smth like this. Not so great idea but i liked it as it will create excitement and curiosity in the user to get a song maybe of this like… 
Hope i am able to make you understand what i am trying to say.

Waiting for ya response and gonna be a contributor in the project soon x:))

**Comment by TheNewC0der-24** [comment]
Thanks, @TEDDY6969 
I understand what your thought processes. So, for that, you can make 2 arrays, one for the Images and one for the songs – make sure that if the 1st element for the song matches the 1st element of the Image (For example : If you put a song named as “XYZ” and the corresponding image for that song is “ABC” so put that in the same index of the array). Then make a random function and pass the array in that. I think this will work. Please let me know after made the changes

**Comment by oyejateen** [comment]
Hey @TheNewC0der-24 , 
I was trying to do that maths.random thing but then idk why but my program was having some issues. I tried to define 4-5 arrays to random but each time only one of them was working fine so i dropped this idea but then i got one more idea as what if we can add buttons in it right… like 5-6 songs attached with buttons and when user will tap on those button our system will load that particular song with the help of on click function.
I have written the code bro but still i am facing some issues like the position of buttons they are like changing the position when I click each wait i show you some examples 
![Screenshot_2022-10-03-18-06-46-08](https://user-images.githubusercontent.com/75193966/193612384-d15b9405-a1f5-493a-b42e-5ca85bc23504.png)
![Screenshot_2022-10-03-18-06-55-99](https://user-images.githubusercontent.com/75193966/193612484-164f3a44-76d2-4e10-86e5-705097a671b0.png)
![Screenshot_2022-10-03-18-07-18-51](https://user-images.githubusercontent.com/75193966/193612626-f6c4e310-9873-40ff-98a2-65279d1d420e.png)


Can you help me out with css thing maybe like the code is almost ready right I'll make a pull request and you can approve it then make the required changes with these buttons thing maybe if you are free… and bro do you have any insta or telegram thing so that I can ask for help (i know it's not so professional thing but just my stupid ass asking for it).

And then how can I give you credit if i host this project I'll be so greatfull to it :))

**Comment by oyejateen** [comment]
Bro so this project it finished i have fixed the buttons thing so thanks alot for all your help.

**Comment by TheNewC0der-24** [comment]
Thanks, @TEDDY6969, for contributing !!
This looks great 🤩

**Comment by TheNewC0der-24** [comment]
Yes, I am on Instagram. Below is my profile link 👇
[Cynophilist](https://www.instagram.com/__cynophilist__._/)

Also, for giving the credits, If you can put my GitHub profile on your application then it would be great.

**Comment by oyejateen** [comment]
Yo, thanks buddy!! I have added your GitHub profile in the main website as well as on the project readme. 

:) Thanks alot
